wordgen: 
	gcc -o wordgen wordgen.c -g -Wall -Wextra -Wpedantic -std=gnu11

wordsearch: 
	gcc -o wordsearch wordsearch.c -g -Wall -Wextra -Wpedantic -std=gnu11

pager: 
	gcc -o pager pager.c -g -Wall -Wextra -Wpedantic -std=gnu11

launcher: 
	gcc -o launcher launcher.c -g -Wall -Wextra -Wpedantic -std=gnu11

clean:
	rm -f *.exe *.o *.stackdump *~
